language: node_js
node_js:
  - '10.15.3'

before_script:
  - npm install

script:
  - npm run build
  - npm run lint
  - npm run lint:scss
  - npm run test:unit

notifications:
  email:
    on_success: never
